// flow-typed signature: 864e57d4ad69707f6e9deb10431cc172
// flow-typed version: <<STUB>>/@mdx-js/tag_vx.x.x/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mdx-js/tag'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mdx-js/tag' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mdx-js/tag/dist/index' {
  declare module.exports: any;
}

declare module '@mdx-js/tag/dist/mdx-provider' {
  declare module.exports: any;
}

declare module '@mdx-js/tag/dist/mdx-tag' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mdx-js/tag/dist/index.js' {
  declare module.exports: $Exports<'@mdx-js/tag/dist/index'>;
}
declare module '@mdx-js/tag/dist/mdx-provider.js' {
  declare module.exports: $Exports<'@mdx-js/tag/dist/mdx-provider'>;
}
declare module '@mdx-js/tag/dist/mdx-tag.js' {
  declare module.exports: $Exports<'@mdx-js/tag/dist/mdx-tag'>;
}
