// flow-typed signature: 10314a0a96760e6afe73f0fad3e35003
// flow-typed version: <<STUB>>/conditional-wrap_v^1.0.0/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'conditional-wrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'conditional-wrap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'conditional-wrap/es/index' {
  declare module.exports: any;
}

declare module 'conditional-wrap/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'conditional-wrap/es/index.js' {
  declare module.exports: $Exports<'conditional-wrap/es/index'>;
}
declare module 'conditional-wrap/lib/index.js' {
  declare module.exports: $Exports<'conditional-wrap/lib/index'>;
}
