// flow-typed signature: 35a753d5e036ca3f66714a112e60a672
// flow-typed version: <<STUB>>/date-fns_v1.x.x/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'date-fns'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'date-fns' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'date-fns/add_days/index' {
  declare module.exports: any;
}

declare module 'date-fns/add_hours/index' {
  declare module.exports: any;
}

declare module 'date-fns/add_iso_years/index' {
  declare module.exports: any;
}

declare module 'date-fns/add_milliseconds/index' {
  declare module.exports: any;
}

declare module 'date-fns/add_minutes/index' {
  declare module.exports: any;
}

declare module 'date-fns/add_months/index' {
  declare module.exports: any;
}

declare module 'date-fns/add_quarters/index' {
  declare module.exports: any;
}

declare module 'date-fns/add_seconds/index' {
  declare module.exports: any;
}

declare module 'date-fns/add_weeks/index' {
  declare module.exports: any;
}

declare module 'date-fns/add_years/index' {
  declare module.exports: any;
}

declare module 'date-fns/are_ranges_overlapping/index' {
  declare module.exports: any;
}

declare module 'date-fns/closest_index_to/index' {
  declare module.exports: any;
}

declare module 'date-fns/closest_to/index' {
  declare module.exports: any;
}

declare module 'date-fns/compare_asc/index' {
  declare module.exports: any;
}

declare module 'date-fns/compare_desc/index' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_calendar_days/index' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_calendar_iso_weeks/index' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_calendar_iso_years/index' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_calendar_months/index' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_calendar_quarters/index' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_calendar_weeks/index' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_calendar_years/index' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_days/index' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_hours/index' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_iso_years/index' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_milliseconds/index' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_minutes/index' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_months/index' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_quarters/index' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_seconds/index' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_weeks/index' {
  declare module.exports: any;
}

declare module 'date-fns/difference_in_years/index' {
  declare module.exports: any;
}

declare module 'date-fns/distance_in_words_strict/index' {
  declare module.exports: any;
}

declare module 'date-fns/distance_in_words_to_now/index' {
  declare module.exports: any;
}

declare module 'date-fns/distance_in_words/index' {
  declare module.exports: any;
}

declare module 'date-fns/each_day/index' {
  declare module.exports: any;
}

declare module 'date-fns/end_of_day/index' {
  declare module.exports: any;
}

declare module 'date-fns/end_of_hour/index' {
  declare module.exports: any;
}

declare module 'date-fns/end_of_iso_week/index' {
  declare module.exports: any;
}

declare module 'date-fns/end_of_iso_year/index' {
  declare module.exports: any;
}

declare module 'date-fns/end_of_minute/index' {
  declare module.exports: any;
}

declare module 'date-fns/end_of_month/index' {
  declare module.exports: any;
}

declare module 'date-fns/end_of_quarter/index' {
  declare module.exports: any;
}

declare module 'date-fns/end_of_second/index' {
  declare module.exports: any;
}

declare module 'date-fns/end_of_today/index' {
  declare module.exports: any;
}

declare module 'date-fns/end_of_tomorrow/index' {
  declare module.exports: any;
}

declare module 'date-fns/end_of_week/index' {
  declare module.exports: any;
}

declare module 'date-fns/end_of_year/index' {
  declare module.exports: any;
}

declare module 'date-fns/end_of_yesterday/index' {
  declare module.exports: any;
}

declare module 'date-fns/format/index' {
  declare module.exports: any;
}

declare module 'date-fns/get_date/index' {
  declare module.exports: any;
}

declare module 'date-fns/get_day_of_year/index' {
  declare module.exports: any;
}

declare module 'date-fns/get_day/index' {
  declare module.exports: any;
}

declare module 'date-fns/get_days_in_month/index' {
  declare module.exports: any;
}

declare module 'date-fns/get_days_in_year/index' {
  declare module.exports: any;
}

declare module 'date-fns/get_hours/index' {
  declare module.exports: any;
}

declare module 'date-fns/get_iso_day/index' {
  declare module.exports: any;
}

declare module 'date-fns/get_iso_week/index' {
  declare module.exports: any;
}

declare module 'date-fns/get_iso_weeks_in_year/index' {
  declare module.exports: any;
}

declare module 'date-fns/get_iso_year/index' {
  declare module.exports: any;
}

declare module 'date-fns/get_milliseconds/index' {
  declare module.exports: any;
}

declare module 'date-fns/get_minutes/index' {
  declare module.exports: any;
}

declare module 'date-fns/get_month/index' {
  declare module.exports: any;
}

declare module 'date-fns/get_overlapping_days_in_ranges/index' {
  declare module.exports: any;
}

declare module 'date-fns/get_quarter/index' {
  declare module.exports: any;
}

declare module 'date-fns/get_seconds/index' {
  declare module.exports: any;
}

declare module 'date-fns/get_time/index' {
  declare module.exports: any;
}

declare module 'date-fns/get_year/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_after/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_before/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_date/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_equal/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_first_day_of_month/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_friday/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_future/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_last_day_of_month/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_leap_year/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_monday/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_past/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_same_day/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_same_hour/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_same_iso_week/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_same_iso_year/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_same_minute/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_same_month/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_same_quarter/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_same_second/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_same_week/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_same_year/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_saturday/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_sunday/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_this_hour/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_this_iso_week/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_this_iso_year/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_this_minute/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_this_month/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_this_quarter/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_this_second/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_this_week/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_this_year/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_thursday/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_today/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_tomorrow/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_tuesday/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_valid/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_wednesday/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_weekend/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_within_range/index' {
  declare module.exports: any;
}

declare module 'date-fns/is_yesterday/index' {
  declare module.exports: any;
}

declare module 'date-fns/last_day_of_iso_week/index' {
  declare module.exports: any;
}

declare module 'date-fns/last_day_of_iso_year/index' {
  declare module.exports: any;
}

declare module 'date-fns/last_day_of_month/index' {
  declare module.exports: any;
}

declare module 'date-fns/last_day_of_quarter/index' {
  declare module.exports: any;
}

declare module 'date-fns/last_day_of_week/index' {
  declare module.exports: any;
}

declare module 'date-fns/last_day_of_year/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/_lib/build_formatting_tokens_reg_exp/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ar/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ar/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ar/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/bg/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/bg/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/bg/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ca/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ca/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ca/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/cs/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/cs/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/cs/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/da/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/da/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/da/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/de/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/de/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/de/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/el/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/el/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/el/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/en/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/en/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/en/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/eo/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/eo/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/eo/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/es/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/es/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/es/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/fi/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/fi/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/fi/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/fil/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/fil/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/fil/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/fr/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/fr/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/fr/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/hr/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/hr/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/hr/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/hu/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/hu/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/hu/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/id/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/id/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/id/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/is/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/is/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/is/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/it/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/it/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/it/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ja/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ja/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ja/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ko/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ko/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ko/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/mk/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/mk/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/mk/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/nb/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/nb/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/nb/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/nl/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/nl/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/nl/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/pl/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/pl/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/pl/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/pt/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/pt/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/pt/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ro/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ro/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ro/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ru/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ru/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/ru/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/sk/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/sk/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/sk/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/sl/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/sl/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/sl/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/sv/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/sv/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/sv/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/th/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/th/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/th/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/tr/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/tr/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/tr/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/zh_cn/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/zh_cn/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/zh_cn/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/zh_tw/build_distance_in_words_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/zh_tw/build_format_locale/index' {
  declare module.exports: any;
}

declare module 'date-fns/locale/zh_tw/index' {
  declare module.exports: any;
}

declare module 'date-fns/max/index' {
  declare module.exports: any;
}

declare module 'date-fns/min/index' {
  declare module.exports: any;
}

declare module 'date-fns/parse/index' {
  declare module.exports: any;
}

declare module 'date-fns/set_date/index' {
  declare module.exports: any;
}

declare module 'date-fns/set_day_of_year/index' {
  declare module.exports: any;
}

declare module 'date-fns/set_day/index' {
  declare module.exports: any;
}

declare module 'date-fns/set_hours/index' {
  declare module.exports: any;
}

declare module 'date-fns/set_iso_day/index' {
  declare module.exports: any;
}

declare module 'date-fns/set_iso_week/index' {
  declare module.exports: any;
}

declare module 'date-fns/set_iso_year/index' {
  declare module.exports: any;
}

declare module 'date-fns/set_milliseconds/index' {
  declare module.exports: any;
}

declare module 'date-fns/set_minutes/index' {
  declare module.exports: any;
}

declare module 'date-fns/set_month/index' {
  declare module.exports: any;
}

declare module 'date-fns/set_quarter/index' {
  declare module.exports: any;
}

declare module 'date-fns/set_seconds/index' {
  declare module.exports: any;
}

declare module 'date-fns/set_year/index' {
  declare module.exports: any;
}

declare module 'date-fns/start_of_day/index' {
  declare module.exports: any;
}

declare module 'date-fns/start_of_hour/index' {
  declare module.exports: any;
}

declare module 'date-fns/start_of_iso_week/index' {
  declare module.exports: any;
}

declare module 'date-fns/start_of_iso_year/index' {
  declare module.exports: any;
}

declare module 'date-fns/start_of_minute/index' {
  declare module.exports: any;
}

declare module 'date-fns/start_of_month/index' {
  declare module.exports: any;
}

declare module 'date-fns/start_of_quarter/index' {
  declare module.exports: any;
}

declare module 'date-fns/start_of_second/index' {
  declare module.exports: any;
}

declare module 'date-fns/start_of_today/index' {
  declare module.exports: any;
}

declare module 'date-fns/start_of_tomorrow/index' {
  declare module.exports: any;
}

declare module 'date-fns/start_of_week/index' {
  declare module.exports: any;
}

declare module 'date-fns/start_of_year/index' {
  declare module.exports: any;
}

declare module 'date-fns/start_of_yesterday/index' {
  declare module.exports: any;
}

declare module 'date-fns/sub_days/index' {
  declare module.exports: any;
}

declare module 'date-fns/sub_hours/index' {
  declare module.exports: any;
}

declare module 'date-fns/sub_iso_years/index' {
  declare module.exports: any;
}

declare module 'date-fns/sub_milliseconds/index' {
  declare module.exports: any;
}

declare module 'date-fns/sub_minutes/index' {
  declare module.exports: any;
}

declare module 'date-fns/sub_months/index' {
  declare module.exports: any;
}

declare module 'date-fns/sub_quarters/index' {
  declare module.exports: any;
}

declare module 'date-fns/sub_seconds/index' {
  declare module.exports: any;
}

declare module 'date-fns/sub_weeks/index' {
  declare module.exports: any;
}

declare module 'date-fns/sub_years/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'date-fns/add_days/index.js' {
  declare module.exports: $Exports<'date-fns/add_days/index'>;
}
declare module 'date-fns/add_hours/index.js' {
  declare module.exports: $Exports<'date-fns/add_hours/index'>;
}
declare module 'date-fns/add_iso_years/index.js' {
  declare module.exports: $Exports<'date-fns/add_iso_years/index'>;
}
declare module 'date-fns/add_milliseconds/index.js' {
  declare module.exports: $Exports<'date-fns/add_milliseconds/index'>;
}
declare module 'date-fns/add_minutes/index.js' {
  declare module.exports: $Exports<'date-fns/add_minutes/index'>;
}
declare module 'date-fns/add_months/index.js' {
  declare module.exports: $Exports<'date-fns/add_months/index'>;
}
declare module 'date-fns/add_quarters/index.js' {
  declare module.exports: $Exports<'date-fns/add_quarters/index'>;
}
declare module 'date-fns/add_seconds/index.js' {
  declare module.exports: $Exports<'date-fns/add_seconds/index'>;
}
declare module 'date-fns/add_weeks/index.js' {
  declare module.exports: $Exports<'date-fns/add_weeks/index'>;
}
declare module 'date-fns/add_years/index.js' {
  declare module.exports: $Exports<'date-fns/add_years/index'>;
}
declare module 'date-fns/are_ranges_overlapping/index.js' {
  declare module.exports: $Exports<'date-fns/are_ranges_overlapping/index'>;
}
declare module 'date-fns/closest_index_to/index.js' {
  declare module.exports: $Exports<'date-fns/closest_index_to/index'>;
}
declare module 'date-fns/closest_to/index.js' {
  declare module.exports: $Exports<'date-fns/closest_to/index'>;
}
declare module 'date-fns/compare_asc/index.js' {
  declare module.exports: $Exports<'date-fns/compare_asc/index'>;
}
declare module 'date-fns/compare_desc/index.js' {
  declare module.exports: $Exports<'date-fns/compare_desc/index'>;
}
declare module 'date-fns/difference_in_calendar_days/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_calendar_days/index'>;
}
declare module 'date-fns/difference_in_calendar_iso_weeks/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_calendar_iso_weeks/index'>;
}
declare module 'date-fns/difference_in_calendar_iso_years/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_calendar_iso_years/index'>;
}
declare module 'date-fns/difference_in_calendar_months/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_calendar_months/index'>;
}
declare module 'date-fns/difference_in_calendar_quarters/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_calendar_quarters/index'>;
}
declare module 'date-fns/difference_in_calendar_weeks/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_calendar_weeks/index'>;
}
declare module 'date-fns/difference_in_calendar_years/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_calendar_years/index'>;
}
declare module 'date-fns/difference_in_days/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_days/index'>;
}
declare module 'date-fns/difference_in_hours/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_hours/index'>;
}
declare module 'date-fns/difference_in_iso_years/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_iso_years/index'>;
}
declare module 'date-fns/difference_in_milliseconds/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_milliseconds/index'>;
}
declare module 'date-fns/difference_in_minutes/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_minutes/index'>;
}
declare module 'date-fns/difference_in_months/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_months/index'>;
}
declare module 'date-fns/difference_in_quarters/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_quarters/index'>;
}
declare module 'date-fns/difference_in_seconds/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_seconds/index'>;
}
declare module 'date-fns/difference_in_weeks/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_weeks/index'>;
}
declare module 'date-fns/difference_in_years/index.js' {
  declare module.exports: $Exports<'date-fns/difference_in_years/index'>;
}
declare module 'date-fns/distance_in_words_strict/index.js' {
  declare module.exports: $Exports<'date-fns/distance_in_words_strict/index'>;
}
declare module 'date-fns/distance_in_words_to_now/index.js' {
  declare module.exports: $Exports<'date-fns/distance_in_words_to_now/index'>;
}
declare module 'date-fns/distance_in_words/index.js' {
  declare module.exports: $Exports<'date-fns/distance_in_words/index'>;
}
declare module 'date-fns/each_day/index.js' {
  declare module.exports: $Exports<'date-fns/each_day/index'>;
}
declare module 'date-fns/end_of_day/index.js' {
  declare module.exports: $Exports<'date-fns/end_of_day/index'>;
}
declare module 'date-fns/end_of_hour/index.js' {
  declare module.exports: $Exports<'date-fns/end_of_hour/index'>;
}
declare module 'date-fns/end_of_iso_week/index.js' {
  declare module.exports: $Exports<'date-fns/end_of_iso_week/index'>;
}
declare module 'date-fns/end_of_iso_year/index.js' {
  declare module.exports: $Exports<'date-fns/end_of_iso_year/index'>;
}
declare module 'date-fns/end_of_minute/index.js' {
  declare module.exports: $Exports<'date-fns/end_of_minute/index'>;
}
declare module 'date-fns/end_of_month/index.js' {
  declare module.exports: $Exports<'date-fns/end_of_month/index'>;
}
declare module 'date-fns/end_of_quarter/index.js' {
  declare module.exports: $Exports<'date-fns/end_of_quarter/index'>;
}
declare module 'date-fns/end_of_second/index.js' {
  declare module.exports: $Exports<'date-fns/end_of_second/index'>;
}
declare module 'date-fns/end_of_today/index.js' {
  declare module.exports: $Exports<'date-fns/end_of_today/index'>;
}
declare module 'date-fns/end_of_tomorrow/index.js' {
  declare module.exports: $Exports<'date-fns/end_of_tomorrow/index'>;
}
declare module 'date-fns/end_of_week/index.js' {
  declare module.exports: $Exports<'date-fns/end_of_week/index'>;
}
declare module 'date-fns/end_of_year/index.js' {
  declare module.exports: $Exports<'date-fns/end_of_year/index'>;
}
declare module 'date-fns/end_of_yesterday/index.js' {
  declare module.exports: $Exports<'date-fns/end_of_yesterday/index'>;
}
declare module 'date-fns/format/index.js' {
  declare module.exports: $Exports<'date-fns/format/index'>;
}
declare module 'date-fns/get_date/index.js' {
  declare module.exports: $Exports<'date-fns/get_date/index'>;
}
declare module 'date-fns/get_day_of_year/index.js' {
  declare module.exports: $Exports<'date-fns/get_day_of_year/index'>;
}
declare module 'date-fns/get_day/index.js' {
  declare module.exports: $Exports<'date-fns/get_day/index'>;
}
declare module 'date-fns/get_days_in_month/index.js' {
  declare module.exports: $Exports<'date-fns/get_days_in_month/index'>;
}
declare module 'date-fns/get_days_in_year/index.js' {
  declare module.exports: $Exports<'date-fns/get_days_in_year/index'>;
}
declare module 'date-fns/get_hours/index.js' {
  declare module.exports: $Exports<'date-fns/get_hours/index'>;
}
declare module 'date-fns/get_iso_day/index.js' {
  declare module.exports: $Exports<'date-fns/get_iso_day/index'>;
}
declare module 'date-fns/get_iso_week/index.js' {
  declare module.exports: $Exports<'date-fns/get_iso_week/index'>;
}
declare module 'date-fns/get_iso_weeks_in_year/index.js' {
  declare module.exports: $Exports<'date-fns/get_iso_weeks_in_year/index'>;
}
declare module 'date-fns/get_iso_year/index.js' {
  declare module.exports: $Exports<'date-fns/get_iso_year/index'>;
}
declare module 'date-fns/get_milliseconds/index.js' {
  declare module.exports: $Exports<'date-fns/get_milliseconds/index'>;
}
declare module 'date-fns/get_minutes/index.js' {
  declare module.exports: $Exports<'date-fns/get_minutes/index'>;
}
declare module 'date-fns/get_month/index.js' {
  declare module.exports: $Exports<'date-fns/get_month/index'>;
}
declare module 'date-fns/get_overlapping_days_in_ranges/index.js' {
  declare module.exports: $Exports<'date-fns/get_overlapping_days_in_ranges/index'>;
}
declare module 'date-fns/get_quarter/index.js' {
  declare module.exports: $Exports<'date-fns/get_quarter/index'>;
}
declare module 'date-fns/get_seconds/index.js' {
  declare module.exports: $Exports<'date-fns/get_seconds/index'>;
}
declare module 'date-fns/get_time/index.js' {
  declare module.exports: $Exports<'date-fns/get_time/index'>;
}
declare module 'date-fns/get_year/index.js' {
  declare module.exports: $Exports<'date-fns/get_year/index'>;
}
declare module 'date-fns/index' {
  declare module.exports: $Exports<'date-fns'>;
}
declare module 'date-fns/index.js' {
  declare module.exports: $Exports<'date-fns'>;
}
declare module 'date-fns/is_after/index.js' {
  declare module.exports: $Exports<'date-fns/is_after/index'>;
}
declare module 'date-fns/is_before/index.js' {
  declare module.exports: $Exports<'date-fns/is_before/index'>;
}
declare module 'date-fns/is_date/index.js' {
  declare module.exports: $Exports<'date-fns/is_date/index'>;
}
declare module 'date-fns/is_equal/index.js' {
  declare module.exports: $Exports<'date-fns/is_equal/index'>;
}
declare module 'date-fns/is_first_day_of_month/index.js' {
  declare module.exports: $Exports<'date-fns/is_first_day_of_month/index'>;
}
declare module 'date-fns/is_friday/index.js' {
  declare module.exports: $Exports<'date-fns/is_friday/index'>;
}
declare module 'date-fns/is_future/index.js' {
  declare module.exports: $Exports<'date-fns/is_future/index'>;
}
declare module 'date-fns/is_last_day_of_month/index.js' {
  declare module.exports: $Exports<'date-fns/is_last_day_of_month/index'>;
}
declare module 'date-fns/is_leap_year/index.js' {
  declare module.exports: $Exports<'date-fns/is_leap_year/index'>;
}
declare module 'date-fns/is_monday/index.js' {
  declare module.exports: $Exports<'date-fns/is_monday/index'>;
}
declare module 'date-fns/is_past/index.js' {
  declare module.exports: $Exports<'date-fns/is_past/index'>;
}
declare module 'date-fns/is_same_day/index.js' {
  declare module.exports: $Exports<'date-fns/is_same_day/index'>;
}
declare module 'date-fns/is_same_hour/index.js' {
  declare module.exports: $Exports<'date-fns/is_same_hour/index'>;
}
declare module 'date-fns/is_same_iso_week/index.js' {
  declare module.exports: $Exports<'date-fns/is_same_iso_week/index'>;
}
declare module 'date-fns/is_same_iso_year/index.js' {
  declare module.exports: $Exports<'date-fns/is_same_iso_year/index'>;
}
declare module 'date-fns/is_same_minute/index.js' {
  declare module.exports: $Exports<'date-fns/is_same_minute/index'>;
}
declare module 'date-fns/is_same_month/index.js' {
  declare module.exports: $Exports<'date-fns/is_same_month/index'>;
}
declare module 'date-fns/is_same_quarter/index.js' {
  declare module.exports: $Exports<'date-fns/is_same_quarter/index'>;
}
declare module 'date-fns/is_same_second/index.js' {
  declare module.exports: $Exports<'date-fns/is_same_second/index'>;
}
declare module 'date-fns/is_same_week/index.js' {
  declare module.exports: $Exports<'date-fns/is_same_week/index'>;
}
declare module 'date-fns/is_same_year/index.js' {
  declare module.exports: $Exports<'date-fns/is_same_year/index'>;
}
declare module 'date-fns/is_saturday/index.js' {
  declare module.exports: $Exports<'date-fns/is_saturday/index'>;
}
declare module 'date-fns/is_sunday/index.js' {
  declare module.exports: $Exports<'date-fns/is_sunday/index'>;
}
declare module 'date-fns/is_this_hour/index.js' {
  declare module.exports: $Exports<'date-fns/is_this_hour/index'>;
}
declare module 'date-fns/is_this_iso_week/index.js' {
  declare module.exports: $Exports<'date-fns/is_this_iso_week/index'>;
}
declare module 'date-fns/is_this_iso_year/index.js' {
  declare module.exports: $Exports<'date-fns/is_this_iso_year/index'>;
}
declare module 'date-fns/is_this_minute/index.js' {
  declare module.exports: $Exports<'date-fns/is_this_minute/index'>;
}
declare module 'date-fns/is_this_month/index.js' {
  declare module.exports: $Exports<'date-fns/is_this_month/index'>;
}
declare module 'date-fns/is_this_quarter/index.js' {
  declare module.exports: $Exports<'date-fns/is_this_quarter/index'>;
}
declare module 'date-fns/is_this_second/index.js' {
  declare module.exports: $Exports<'date-fns/is_this_second/index'>;
}
declare module 'date-fns/is_this_week/index.js' {
  declare module.exports: $Exports<'date-fns/is_this_week/index'>;
}
declare module 'date-fns/is_this_year/index.js' {
  declare module.exports: $Exports<'date-fns/is_this_year/index'>;
}
declare module 'date-fns/is_thursday/index.js' {
  declare module.exports: $Exports<'date-fns/is_thursday/index'>;
}
declare module 'date-fns/is_today/index.js' {
  declare module.exports: $Exports<'date-fns/is_today/index'>;
}
declare module 'date-fns/is_tomorrow/index.js' {
  declare module.exports: $Exports<'date-fns/is_tomorrow/index'>;
}
declare module 'date-fns/is_tuesday/index.js' {
  declare module.exports: $Exports<'date-fns/is_tuesday/index'>;
}
declare module 'date-fns/is_valid/index.js' {
  declare module.exports: $Exports<'date-fns/is_valid/index'>;
}
declare module 'date-fns/is_wednesday/index.js' {
  declare module.exports: $Exports<'date-fns/is_wednesday/index'>;
}
declare module 'date-fns/is_weekend/index.js' {
  declare module.exports: $Exports<'date-fns/is_weekend/index'>;
}
declare module 'date-fns/is_within_range/index.js' {
  declare module.exports: $Exports<'date-fns/is_within_range/index'>;
}
declare module 'date-fns/is_yesterday/index.js' {
  declare module.exports: $Exports<'date-fns/is_yesterday/index'>;
}
declare module 'date-fns/last_day_of_iso_week/index.js' {
  declare module.exports: $Exports<'date-fns/last_day_of_iso_week/index'>;
}
declare module 'date-fns/last_day_of_iso_year/index.js' {
  declare module.exports: $Exports<'date-fns/last_day_of_iso_year/index'>;
}
declare module 'date-fns/last_day_of_month/index.js' {
  declare module.exports: $Exports<'date-fns/last_day_of_month/index'>;
}
declare module 'date-fns/last_day_of_quarter/index.js' {
  declare module.exports: $Exports<'date-fns/last_day_of_quarter/index'>;
}
declare module 'date-fns/last_day_of_week/index.js' {
  declare module.exports: $Exports<'date-fns/last_day_of_week/index'>;
}
declare module 'date-fns/last_day_of_year/index.js' {
  declare module.exports: $Exports<'date-fns/last_day_of_year/index'>;
}
declare module 'date-fns/locale/_lib/build_formatting_tokens_reg_exp/index.js' {
  declare module.exports: $Exports<'date-fns/locale/_lib/build_formatting_tokens_reg_exp/index'>;
}
declare module 'date-fns/locale/ar/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ar/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/ar/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ar/build_format_locale/index'>;
}
declare module 'date-fns/locale/ar/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ar/index'>;
}
declare module 'date-fns/locale/bg/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/bg/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/bg/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/bg/build_format_locale/index'>;
}
declare module 'date-fns/locale/bg/index.js' {
  declare module.exports: $Exports<'date-fns/locale/bg/index'>;
}
declare module 'date-fns/locale/ca/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ca/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/ca/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ca/build_format_locale/index'>;
}
declare module 'date-fns/locale/ca/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ca/index'>;
}
declare module 'date-fns/locale/cs/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/cs/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/cs/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/cs/build_format_locale/index'>;
}
declare module 'date-fns/locale/cs/index.js' {
  declare module.exports: $Exports<'date-fns/locale/cs/index'>;
}
declare module 'date-fns/locale/da/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/da/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/da/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/da/build_format_locale/index'>;
}
declare module 'date-fns/locale/da/index.js' {
  declare module.exports: $Exports<'date-fns/locale/da/index'>;
}
declare module 'date-fns/locale/de/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/de/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/de/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/de/build_format_locale/index'>;
}
declare module 'date-fns/locale/de/index.js' {
  declare module.exports: $Exports<'date-fns/locale/de/index'>;
}
declare module 'date-fns/locale/el/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/el/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/el/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/el/build_format_locale/index'>;
}
declare module 'date-fns/locale/el/index.js' {
  declare module.exports: $Exports<'date-fns/locale/el/index'>;
}
declare module 'date-fns/locale/en/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/en/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/en/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/en/build_format_locale/index'>;
}
declare module 'date-fns/locale/en/index.js' {
  declare module.exports: $Exports<'date-fns/locale/en/index'>;
}
declare module 'date-fns/locale/eo/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/eo/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/eo/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/eo/build_format_locale/index'>;
}
declare module 'date-fns/locale/eo/index.js' {
  declare module.exports: $Exports<'date-fns/locale/eo/index'>;
}
declare module 'date-fns/locale/es/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/es/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/es/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/es/build_format_locale/index'>;
}
declare module 'date-fns/locale/es/index.js' {
  declare module.exports: $Exports<'date-fns/locale/es/index'>;
}
declare module 'date-fns/locale/fi/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/fi/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/fi/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/fi/build_format_locale/index'>;
}
declare module 'date-fns/locale/fi/index.js' {
  declare module.exports: $Exports<'date-fns/locale/fi/index'>;
}
declare module 'date-fns/locale/fil/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/fil/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/fil/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/fil/build_format_locale/index'>;
}
declare module 'date-fns/locale/fil/index.js' {
  declare module.exports: $Exports<'date-fns/locale/fil/index'>;
}
declare module 'date-fns/locale/fr/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/fr/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/fr/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/fr/build_format_locale/index'>;
}
declare module 'date-fns/locale/fr/index.js' {
  declare module.exports: $Exports<'date-fns/locale/fr/index'>;
}
declare module 'date-fns/locale/hr/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/hr/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/hr/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/hr/build_format_locale/index'>;
}
declare module 'date-fns/locale/hr/index.js' {
  declare module.exports: $Exports<'date-fns/locale/hr/index'>;
}
declare module 'date-fns/locale/hu/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/hu/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/hu/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/hu/build_format_locale/index'>;
}
declare module 'date-fns/locale/hu/index.js' {
  declare module.exports: $Exports<'date-fns/locale/hu/index'>;
}
declare module 'date-fns/locale/id/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/id/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/id/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/id/build_format_locale/index'>;
}
declare module 'date-fns/locale/id/index.js' {
  declare module.exports: $Exports<'date-fns/locale/id/index'>;
}
declare module 'date-fns/locale/is/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/is/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/is/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/is/build_format_locale/index'>;
}
declare module 'date-fns/locale/is/index.js' {
  declare module.exports: $Exports<'date-fns/locale/is/index'>;
}
declare module 'date-fns/locale/it/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/it/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/it/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/it/build_format_locale/index'>;
}
declare module 'date-fns/locale/it/index.js' {
  declare module.exports: $Exports<'date-fns/locale/it/index'>;
}
declare module 'date-fns/locale/ja/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ja/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/ja/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ja/build_format_locale/index'>;
}
declare module 'date-fns/locale/ja/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ja/index'>;
}
declare module 'date-fns/locale/ko/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ko/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/ko/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ko/build_format_locale/index'>;
}
declare module 'date-fns/locale/ko/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ko/index'>;
}
declare module 'date-fns/locale/mk/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/mk/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/mk/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/mk/build_format_locale/index'>;
}
declare module 'date-fns/locale/mk/index.js' {
  declare module.exports: $Exports<'date-fns/locale/mk/index'>;
}
declare module 'date-fns/locale/nb/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/nb/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/nb/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/nb/build_format_locale/index'>;
}
declare module 'date-fns/locale/nb/index.js' {
  declare module.exports: $Exports<'date-fns/locale/nb/index'>;
}
declare module 'date-fns/locale/nl/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/nl/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/nl/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/nl/build_format_locale/index'>;
}
declare module 'date-fns/locale/nl/index.js' {
  declare module.exports: $Exports<'date-fns/locale/nl/index'>;
}
declare module 'date-fns/locale/pl/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/pl/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/pl/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/pl/build_format_locale/index'>;
}
declare module 'date-fns/locale/pl/index.js' {
  declare module.exports: $Exports<'date-fns/locale/pl/index'>;
}
declare module 'date-fns/locale/pt/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/pt/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/pt/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/pt/build_format_locale/index'>;
}
declare module 'date-fns/locale/pt/index.js' {
  declare module.exports: $Exports<'date-fns/locale/pt/index'>;
}
declare module 'date-fns/locale/ro/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ro/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/ro/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ro/build_format_locale/index'>;
}
declare module 'date-fns/locale/ro/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ro/index'>;
}
declare module 'date-fns/locale/ru/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ru/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/ru/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ru/build_format_locale/index'>;
}
declare module 'date-fns/locale/ru/index.js' {
  declare module.exports: $Exports<'date-fns/locale/ru/index'>;
}
declare module 'date-fns/locale/sk/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/sk/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/sk/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/sk/build_format_locale/index'>;
}
declare module 'date-fns/locale/sk/index.js' {
  declare module.exports: $Exports<'date-fns/locale/sk/index'>;
}
declare module 'date-fns/locale/sl/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/sl/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/sl/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/sl/build_format_locale/index'>;
}
declare module 'date-fns/locale/sl/index.js' {
  declare module.exports: $Exports<'date-fns/locale/sl/index'>;
}
declare module 'date-fns/locale/sv/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/sv/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/sv/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/sv/build_format_locale/index'>;
}
declare module 'date-fns/locale/sv/index.js' {
  declare module.exports: $Exports<'date-fns/locale/sv/index'>;
}
declare module 'date-fns/locale/th/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/th/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/th/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/th/build_format_locale/index'>;
}
declare module 'date-fns/locale/th/index.js' {
  declare module.exports: $Exports<'date-fns/locale/th/index'>;
}
declare module 'date-fns/locale/tr/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/tr/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/tr/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/tr/build_format_locale/index'>;
}
declare module 'date-fns/locale/tr/index.js' {
  declare module.exports: $Exports<'date-fns/locale/tr/index'>;
}
declare module 'date-fns/locale/zh_cn/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/zh_cn/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/zh_cn/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/zh_cn/build_format_locale/index'>;
}
declare module 'date-fns/locale/zh_cn/index.js' {
  declare module.exports: $Exports<'date-fns/locale/zh_cn/index'>;
}
declare module 'date-fns/locale/zh_tw/build_distance_in_words_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/zh_tw/build_distance_in_words_locale/index'>;
}
declare module 'date-fns/locale/zh_tw/build_format_locale/index.js' {
  declare module.exports: $Exports<'date-fns/locale/zh_tw/build_format_locale/index'>;
}
declare module 'date-fns/locale/zh_tw/index.js' {
  declare module.exports: $Exports<'date-fns/locale/zh_tw/index'>;
}
declare module 'date-fns/max/index.js' {
  declare module.exports: $Exports<'date-fns/max/index'>;
}
declare module 'date-fns/min/index.js' {
  declare module.exports: $Exports<'date-fns/min/index'>;
}
declare module 'date-fns/parse/index.js' {
  declare module.exports: $Exports<'date-fns/parse/index'>;
}
declare module 'date-fns/set_date/index.js' {
  declare module.exports: $Exports<'date-fns/set_date/index'>;
}
declare module 'date-fns/set_day_of_year/index.js' {
  declare module.exports: $Exports<'date-fns/set_day_of_year/index'>;
}
declare module 'date-fns/set_day/index.js' {
  declare module.exports: $Exports<'date-fns/set_day/index'>;
}
declare module 'date-fns/set_hours/index.js' {
  declare module.exports: $Exports<'date-fns/set_hours/index'>;
}
declare module 'date-fns/set_iso_day/index.js' {
  declare module.exports: $Exports<'date-fns/set_iso_day/index'>;
}
declare module 'date-fns/set_iso_week/index.js' {
  declare module.exports: $Exports<'date-fns/set_iso_week/index'>;
}
declare module 'date-fns/set_iso_year/index.js' {
  declare module.exports: $Exports<'date-fns/set_iso_year/index'>;
}
declare module 'date-fns/set_milliseconds/index.js' {
  declare module.exports: $Exports<'date-fns/set_milliseconds/index'>;
}
declare module 'date-fns/set_minutes/index.js' {
  declare module.exports: $Exports<'date-fns/set_minutes/index'>;
}
declare module 'date-fns/set_month/index.js' {
  declare module.exports: $Exports<'date-fns/set_month/index'>;
}
declare module 'date-fns/set_quarter/index.js' {
  declare module.exports: $Exports<'date-fns/set_quarter/index'>;
}
declare module 'date-fns/set_seconds/index.js' {
  declare module.exports: $Exports<'date-fns/set_seconds/index'>;
}
declare module 'date-fns/set_year/index.js' {
  declare module.exports: $Exports<'date-fns/set_year/index'>;
}
declare module 'date-fns/start_of_day/index.js' {
  declare module.exports: $Exports<'date-fns/start_of_day/index'>;
}
declare module 'date-fns/start_of_hour/index.js' {
  declare module.exports: $Exports<'date-fns/start_of_hour/index'>;
}
declare module 'date-fns/start_of_iso_week/index.js' {
  declare module.exports: $Exports<'date-fns/start_of_iso_week/index'>;
}
declare module 'date-fns/start_of_iso_year/index.js' {
  declare module.exports: $Exports<'date-fns/start_of_iso_year/index'>;
}
declare module 'date-fns/start_of_minute/index.js' {
  declare module.exports: $Exports<'date-fns/start_of_minute/index'>;
}
declare module 'date-fns/start_of_month/index.js' {
  declare module.exports: $Exports<'date-fns/start_of_month/index'>;
}
declare module 'date-fns/start_of_quarter/index.js' {
  declare module.exports: $Exports<'date-fns/start_of_quarter/index'>;
}
declare module 'date-fns/start_of_second/index.js' {
  declare module.exports: $Exports<'date-fns/start_of_second/index'>;
}
declare module 'date-fns/start_of_today/index.js' {
  declare module.exports: $Exports<'date-fns/start_of_today/index'>;
}
declare module 'date-fns/start_of_tomorrow/index.js' {
  declare module.exports: $Exports<'date-fns/start_of_tomorrow/index'>;
}
declare module 'date-fns/start_of_week/index.js' {
  declare module.exports: $Exports<'date-fns/start_of_week/index'>;
}
declare module 'date-fns/start_of_year/index.js' {
  declare module.exports: $Exports<'date-fns/start_of_year/index'>;
}
declare module 'date-fns/start_of_yesterday/index.js' {
  declare module.exports: $Exports<'date-fns/start_of_yesterday/index'>;
}
declare module 'date-fns/sub_days/index.js' {
  declare module.exports: $Exports<'date-fns/sub_days/index'>;
}
declare module 'date-fns/sub_hours/index.js' {
  declare module.exports: $Exports<'date-fns/sub_hours/index'>;
}
declare module 'date-fns/sub_iso_years/index.js' {
  declare module.exports: $Exports<'date-fns/sub_iso_years/index'>;
}
declare module 'date-fns/sub_milliseconds/index.js' {
  declare module.exports: $Exports<'date-fns/sub_milliseconds/index'>;
}
declare module 'date-fns/sub_minutes/index.js' {
  declare module.exports: $Exports<'date-fns/sub_minutes/index'>;
}
declare module 'date-fns/sub_months/index.js' {
  declare module.exports: $Exports<'date-fns/sub_months/index'>;
}
declare module 'date-fns/sub_quarters/index.js' {
  declare module.exports: $Exports<'date-fns/sub_quarters/index'>;
}
declare module 'date-fns/sub_seconds/index.js' {
  declare module.exports: $Exports<'date-fns/sub_seconds/index'>;
}
declare module 'date-fns/sub_weeks/index.js' {
  declare module.exports: $Exports<'date-fns/sub_weeks/index'>;
}
declare module 'date-fns/sub_years/index.js' {
  declare module.exports: $Exports<'date-fns/sub_years/index'>;
}
