// flow-typed signature: de8ff263c43b5fd97bca47fcc17b2263
// flow-typed version: <<STUB>>/next-ga_vx.x.x/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-ga'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-ga' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next-ga/dist/analytics/dev' {
  declare module.exports: any;
}

declare module 'next-ga/dist/analytics/prod' {
  declare module.exports: any;
}

declare module 'next-ga/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'next-ga/dist/analytics/dev.js' {
  declare module.exports: $Exports<'next-ga/dist/analytics/dev'>;
}
declare module 'next-ga/dist/analytics/prod.js' {
  declare module.exports: $Exports<'next-ga/dist/analytics/prod'>;
}
declare module 'next-ga/dist/index.js' {
  declare module.exports: $Exports<'next-ga/dist/index'>;
}
declare module 'next-ga/index' {
  declare module.exports: $Exports<'next-ga'>;
}
declare module 'next-ga/index.js' {
  declare module.exports: $Exports<'next-ga'>;
}
