// flow-typed signature: 76ae9f2df100e06e471ed7c9db86dd14
// flow-typed version: <<STUB>>/react-slick_v^0.23.1/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-slick'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-slick' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-slick/dist/react-slick' {
  declare module.exports: any;
}

declare module 'react-slick/dist/react-slick.min' {
  declare module.exports: any;
}

declare module 'react-slick/lib/arrows' {
  declare module.exports: any;
}

declare module 'react-slick/lib/default-props' {
  declare module.exports: any;
}

declare module 'react-slick/lib/dots' {
  declare module.exports: any;
}

declare module 'react-slick/lib/index' {
  declare module.exports: any;
}

declare module 'react-slick/lib/initial-state' {
  declare module.exports: any;
}

declare module 'react-slick/lib/inner-slider' {
  declare module.exports: any;
}

declare module 'react-slick/lib/mixins/event-handlers' {
  declare module.exports: any;
}

declare module 'react-slick/lib/mixins/helpers' {
  declare module.exports: any;
}

declare module 'react-slick/lib/mixins/trackHelper' {
  declare module.exports: any;
}

declare module 'react-slick/lib/slider' {
  declare module.exports: any;
}

declare module 'react-slick/lib/track' {
  declare module.exports: any;
}

declare module 'react-slick/lib/utils/innerSliderUtils' {
  declare module.exports: any;
}

declare module 'react-slick/lib/utils/trackUtils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-slick/dist/react-slick.js' {
  declare module.exports: $Exports<'react-slick/dist/react-slick'>;
}
declare module 'react-slick/dist/react-slick.min.js' {
  declare module.exports: $Exports<'react-slick/dist/react-slick.min'>;
}
declare module 'react-slick/lib/arrows.js' {
  declare module.exports: $Exports<'react-slick/lib/arrows'>;
}
declare module 'react-slick/lib/default-props.js' {
  declare module.exports: $Exports<'react-slick/lib/default-props'>;
}
declare module 'react-slick/lib/dots.js' {
  declare module.exports: $Exports<'react-slick/lib/dots'>;
}
declare module 'react-slick/lib/index.js' {
  declare module.exports: $Exports<'react-slick/lib/index'>;
}
declare module 'react-slick/lib/initial-state.js' {
  declare module.exports: $Exports<'react-slick/lib/initial-state'>;
}
declare module 'react-slick/lib/inner-slider.js' {
  declare module.exports: $Exports<'react-slick/lib/inner-slider'>;
}
declare module 'react-slick/lib/mixins/event-handlers.js' {
  declare module.exports: $Exports<'react-slick/lib/mixins/event-handlers'>;
}
declare module 'react-slick/lib/mixins/helpers.js' {
  declare module.exports: $Exports<'react-slick/lib/mixins/helpers'>;
}
declare module 'react-slick/lib/mixins/trackHelper.js' {
  declare module.exports: $Exports<'react-slick/lib/mixins/trackHelper'>;
}
declare module 'react-slick/lib/slider.js' {
  declare module.exports: $Exports<'react-slick/lib/slider'>;
}
declare module 'react-slick/lib/track.js' {
  declare module.exports: $Exports<'react-slick/lib/track'>;
}
declare module 'react-slick/lib/utils/innerSliderUtils.js' {
  declare module.exports: $Exports<'react-slick/lib/utils/innerSliderUtils'>;
}
declare module 'react-slick/lib/utils/trackUtils.js' {
  declare module.exports: $Exports<'react-slick/lib/utils/trackUtils'>;
}
