// flow-typed signature: bd95b2b46024757873509702f559c4b8
// flow-typed version: <<STUB>>/rebass_v^3.0.0-9/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rebass'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rebass' {
  declare module.exports: any;
}

export type RebassProps = any;

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rebass/dist/emotion/index' {
  declare module.exports: any;
}

declare module 'rebass/dist/index' {
  declare module.exports: any;
}

declare module 'rebass/emotion' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rebass/dist/emotion/index.js' {
  declare module.exports: $Exports<'rebass/dist/emotion/index'>;
}
declare module 'rebass/dist/index.js' {
  declare module.exports: $Exports<'rebass/dist/index'>;
}
declare module 'rebass/emotion.js' {
  declare module.exports: $Exports<'rebass/emotion'>;
}
