// flow-typed signature: 47110a4174220862db3871bb7ab7a5fc
// flow-typed version: <<STUB>>/@babel/plugin-proposal-optional-chaining_v^7.0.0-beta.55/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-optional-chaining'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-optional-chaining' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-optional-chaining/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-optional-chaining/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-optional-chaining/lib/index'>;
}
