// AUTO-GENERATED BY update-notes.ts

export const notes = [
  {
    updatedAt: '2024-06-03T16:28',
    name: '1-on-1 (template)',
    href: 'https://mxstbr.com/notes/1-on-1+(template)',
  },
  {
    updatedAt: '2024-06-03T16:28',
    name: 'Architectural Decision Record (ADR) Template',
    href: 'https://mxstbr.com/notes/Architectural+Decision+Record+(ADR)+Template',
  },
  {
    updatedAt: '2024-06-03T16:28',
    name: 'Developer tools are different than tools for any other profession',
    href: 'https://mxstbr.com/notes/Developer+tools+are+different+than+tools+for+any+other+profession',
  },
  {
    updatedAt: '2024-06-03T16:28',
    name: 'Developer tools startups are almost impossible',
    href: 'https://mxstbr.com/notes/Developer+tools+startups+are+almost+impossible',
  },
  {
    updatedAt: '2024-08-09T16:54',
    name: 'Do checkin questions at the beginning of every meeting to encourage connection',
    href: 'https://mxstbr.com/notes/Do+checkin+questions+at+the+beginning+of+every+meeting+to+encourage+connection',
  },
  {
    updatedAt: '2024-06-03T16:27',
    name: 'How I think about 1-on-1s',
    href: 'https://mxstbr.com/notes/How+I+think+about+1-on-1s',
  },
  {
    updatedAt: '2024-06-03T16:27',
    name: 'Kernel of good strategy (Template)',
    href: 'https://mxstbr.com/notes/Kernel+of+good+strategy+(Template)',
  },
  {
    updatedAt: '2024-06-03T16:27',
    name: 'Recurring meeting notes (Template)',
    href: 'https://mxstbr.com/notes/Recurring+meeting+notes+(Template)',
  },
  {
    updatedAt: '2024-08-09T16:57',
    name: 'Thoughts on using Obsidian for notes',
    href: 'https://mxstbr.com/notes/Thoughts+on+using+Obsidian+for+notes',
  },
  {
    updatedAt: '2024-06-03T16:27',
    name: 'Welcome to my notes!',
    href: 'https://mxstbr.com/notes/Welcome+to+my+notes!',
  },
]
