// AUTO-GENERATED BY update-notes.ts

export const notes = [
  {
    updatedAt: '2024-05-24T15:05',
    name: 'Kernel of good strategy (Template).md',
    href: 'https://mxstbr.com/notes/Kernel+of+good+strategy+(Template)',
  },
  {
    updatedAt: '2024-05-20T07:31',
    name: 'Developer tools startups are almost impossible.md',
    href: 'https://mxstbr.com/notes/Developer+tools+startups+are+almost+impossible',
  },
  {
    updatedAt: '2024-05-20T07:32',
    name: 'Developer tools are different than tools for any other profession.md',
    href: 'https://mxstbr.com/notes/Developer+tools+are+different+than+tools+for+any+other+profession',
  },
  {
    updatedAt: '2024-05-20T08:23',
    name: 'Welcome to my notes!.md',
    href: 'https://mxstbr.com/notes/Welcome+to+my+notes!',
  },
]
