// AUTO-GENERATED BY update-notes.ts

export const notes = [
  {
    updatedAt: '2024-05-24T15:33',
    name: '1-on-1 (template)',
    href: 'https://mxstbr.com/notes/1-on-1+(template)',
  },
  {
    updatedAt: '2024-05-24T15:33',
    name: 'How I think about 1-on-1s',
    href: 'https://mxstbr.com/notes/How+I+think+about+1-on-1s',
  },
  {
    updatedAt: '2024-05-20T07:31',
    name: 'Developer tools startups are almost impossible',
    href: 'https://mxstbr.com/notes/Developer+tools+startups+are+almost+impossible',
  },
  {
    updatedAt: '2024-05-20T07:32',
    name: 'Developer tools are different than tools for any other profession',
    href: 'https://mxstbr.com/notes/Developer+tools+are+different+than+tools+for+any+other+profession',
  },
  {
    updatedAt: '2024-05-20T08:23',
    name: 'Welcome to my notes!',
    href: 'https://mxstbr.com/notes/Welcome+to+my+notes!',
  },
  {
    updatedAt: '2024-05-24T15:05',
    name: 'Kernel of good strategy (Template)',
    href: 'https://mxstbr.com/notes/Kernel+of+good+strategy+(Template)',
  },
]
