// flow-typed signature: c6e814fb0dff51d4df747b203fb8b501
// flow-typed version: <<STUB>>/@next/mdx_v^1.1.0/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@next/mdx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@next/mdx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@next/mdx/index' {
  declare module.exports: $Exports<'@next/mdx'>;
}
declare module '@next/mdx/index.js' {
  declare module.exports: $Exports<'@next/mdx'>;
}
